name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting ENV values
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      uses: docker/login-action@v1.8.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USER }} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASS  }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cyberstriker/actions-lab
    - name: Aqua Security Trivy
      # You may pin to the exact commit or the version.
      # uses: aquasecurity/trivy-action@341f810bd602419f966a081da3f4debedc3e5c8e
      uses: aquasecurity/trivy-action@0.0.15
      with:
        # Scan type to use for scanning vulnerability
        scan-type: image # optional, default is image
        # image reference(for backward compatibility)
        image-ref: cyberstriker/actions-lab
        exit-code: 1
        severity: HIGH,CRITICAL
 
    - name: Push the Docker image
      run: docker push cyberstriker/actions-lab

   
 
