name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting ENV values
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
 

   
 
